### ISSUE TITLE
is this a bug?

### ISSUE THREAD

**Issue by daxiangxiaoyi** [11hhlin1/short-text-classify#1]
1.我是按照您的步骤来的，最后一步执行run的时候，出现如下错误？试了其他的也不行，请问怎么回事

Configuring CNN model...
Configuring TensorBoard and Saver...
Loading training and validation data...
Traceback (most recent call last):
  File "run_cnn.py", line 188, in <module>
    train()
  File "run_cnn.py", line 71, in train
    x_train, y_train = process_file(train_dir, word_to_id, cat_to_id, config.seq_length)
  File "/home/zz/work/github_daxiang/short-text-classify/data/cnews_loader.py", line 70, in process_file
    label_id.append(cat_to_id[labels[i]])
KeyError: u'\u4f53\u80b2'

**Comment by 11hhlin1** [comment]
不是bug的问题，你看下是不是python版本问题，我用的python3.6

**Comment by daxiangxiaoyi** [comment]
谢谢，换成３.5后问题就解决了，可是我换成自己的样本后，又出现问题
`  File "run_cnn.py", line 188, in <module>
    train()
  File "run_cnn.py", line 72, in train
    x_val, y_val = process_file(val_dir, word_to_id, cat_to_id, config.seq_length)
  File "/home/zz/work/github_daxiang/short-text-classify/data/cnews_loader.py", line 74, in process_file
    y_pad = kr.utils.to_categorical(label_id)  # 将标签转换为one-hot表示
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/utils/np_utils.py", line 38, in to_categorical
    num_classes = np.max(y) + 1
  File "/usr/local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 2272, in amax
    out=out, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity
`
我自己找了半天没有找到问题所在，这是怎么回事啊？

**Comment by 11hhlin1** [comment]
应该是你词汇表的问题，你看看vocab文件

**Comment by daxiangxiaoyi** [comment]
我的数据里有０,该怎么处理啊？
